# Generated by Django 4.0.4 on 2022-12-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=400)),
                ('foto', models.CharField(max_length=400)),
                ('descripcion', models.CharField(max_length=400)),
                ('tag', models.CharField(max_length=400)),
                ('url', models.CharField(max_length=400)),
            ],
        ),
    ]
